name: CI - Testes e Cobertura

on:
  push:
  pull_request:

jobs:
  build-test-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependências e executar testes
        run: |
          cd catalogo-carrinho
          mvn -q clean test

      - name: Gerar relatório JaCoCo
        run: |
          cd catalogo-carrinho
          mvn jacoco:report

      - name: Publicar artefatos (cobertura)
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-jacoco
          path: catalogo-carrinho/target/site/jacoco
